export const root: string;
export const stats: string;
export const selectOverride: string;
export const sunburst: string;
export const filename: string;
export const infoInner: string;
export const contents: string;
export const size: string;
export const type: string;
